### ISSUE TITLE
WebSocket APIs for Skip

### ISSUE THREAD

**Issue by paytontech** [skiptools/skip#106]
WebSockets are a very important technology for modern real-time app development. There are many apps that use WebSockets heavily (including many of my own), which Skip cannot support because they have not been implemented.

Swift's `URLSession` has a built-in `webSocketTask`, and it would be great to see this implemented in Skip. I'd love to contribute to this, as it is very important functionality that my app needs to work, and I am very optimistic about Skip, I'm just not sure where I'd start.

**Comment by aabewhite** [comment]
skip-foundation 0.6.0 supports URLSessionWebSocketTask! It is not well tested yet, so please let us know if you run into any issues

**Comment by ajayjapan** [comment]
@aabewhite Receiving the error when I use URLSessionWebSocketTask

```
receive error: Error Domain=NSURLErrorDomain Code=-1002 "(null)"UserInfo={NSErrorFailingURLStringKey=wss://example.com/socket.io/?EIO=4&transport=websocket, NSLocalizedDescription=WebSockets not supported by libcurl, NSErrorFailingURLKey=wss://example.com/socket.io/?EIO=4&transport=websocket}
```

Any suggestions or fixes would be much appreciated.

New Issue: https://github.com/skiptools/skip/issues/559

**Comment by marcprux** [comment]
Unfortunately, our skip-foundation support for WebSockets is only in transpiled Skip Lite, and it looks like you are using Skip Fuse. I'll follow-up in https://github.com/skiptools/skip/issues/559.
