### ISSUE TITLE
Small BUG: 'skip checkup' and 'skip doctor' cant find JetBrains installed Android Studio

### ISSUE THREAD

**Issue by adamhill** [skiptools/skip#107]
The `checkup` and `doctor` commands cannot find an Android Studio Install that was done with JetBrains Tools. It **is** installed in the `~/Applications/` folder. But `checkup` does compile the app just fine.

### **Command line**
<img width="816" alt="image" src="https://github.com/skiptools/skip/assets/188638/a70f92b8-53c3-4c2a-9abc-ea83df0c2f2d">

### **Installation**
<img width="503" alt="image" src="https://github.com/skiptools/skip/assets/188638/098148e3-c668-471c-942e-7ffa9ae500e2">

### **Installation Location**
<img width="454" alt="image" src="https://github.com/skiptools/skip/assets/188638/283c7f85-dba7-4805-93b6-607ed22f0355">

**Comment by marcprux** [comment]
FYI, the next version of the tool will look in `~/Applications/Android Studio.app` as well as the other standard locations (`/Applications/Android Studio.app` and `/Applications/JetBrains Toolbox/Android Studio.app`).

Thanks for the report, and let us know if we can help with anything else!

**Comment by adamhill** [comment]
It is the default location. Thanks.
