### ISSUE TITLE
Requires license in free mode

### ISSUE THREAD

**Issue by wangyiwei2015** [skiptools/skip#108]
I have generated my open-source project with `--free`, but when building skip.tools still checks the license and fails.
![2024-04-20 11 58 06](https://github.com/skiptools/skip/assets/15167959/cefbfb57-cc9c-4b01-ba42-3074769cab5b)

**Comment by wangyiwei2015** [comment]
The statement at the top of source files are added automatically
![2024-04-20 11 59 27](https://github.com/skiptools/skip/assets/15167959/df6ff777-7437-4270-ad3b-e195ee652607)

Skip 0.8.31
Xcode 15.3
macOS 14.4.1

**Comment by marcprux** [comment]
Thanks for the report. We've fixed the problem and released skip-foundation 0.6.4 – please run Xcode's `File` / `Packages` / `Update to Latest Package Versions` and try again, and let us know if the issue persists.
