### ISSUE TITLE
skip checkup passes, but I'm unable to compile HelloSkip

### ISSUE THREAD

**Issue by ssxray** [skiptools/skip#111]
### Discussed in https://github.com/skiptools/skip/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **cromotron** February 25, 2024</sup>
I receive the following error message 
An error occurred while performing transpilation: expected colon, near ""
</div>
I'm having the same issue.  Skip checkup works fine.  When I run Hello skip the build fails - [✗] Build hello-skip (24.08s),  [✗] Skip 0.8.36 init failed with 1 error, and the error in the output file states:
note: Skip 0.8.36: transpile plugin to: /Users/ssxray/hello-skip/.build/plugins/outputs/hello-skip/HelloSkip/skipstone/HelloSkip/src/main at 09:46:13
error: An error occurred while performing transpilation: expected colon, near ""
Error: expected colon, near ""
Any suggestions?
[skip-init-2024-04-26T14:44:57Z.txt](https://github.com/skiptools/skip/files/15133269/skip-init-2024-04-26T14.44.57Z.txt)

**Comment by marcprux** [comment]
Is this happening when you run `skip init`? Can you post the complete command you are running?

It may be that there is some invalid character in your `appid` or project name. Does the error occur if you run this exact command?

```
skip init --open-xcode --appid=bundle.id project-name HelloSkip
```

**Comment by marcprux** [comment]
Oh wait, I think the problem might be your `~/.skiptools/skipkey.env` file. If you have a license key in there, can you make sure the file is valid YAML, like so:

```yaml
SKIPKEY: SKP1234
```

**Comment by ssxray** [comment]
Yes it is.  I first tried to use a different project name, and got the same error. Then I ran that exact command (copied and pasted from the instructions) and again got the same error.
But, you got it entirely right:
The skipkey.env file had a carriage return after SKIPKEY:  (as it was shown in my subscription confirmation email) so that it looked like:
SKIPKEY:
SKP1234
When I removed the carriage return, that error was eliminated.  Unfortunately the xcode project still had errors.
(The two other issues: 
Execution failed for task ':app:installDebug' and 
The gradle command failed. Review the log for details and consult https://skip.tools/docs/faq for common solutions. Command: gradle -p ../Android launchDebug)

**Comment by marcprux** [comment]
Glad to hear that fixing the skipkey.env file resolved the first problem. 

The subsequent Xcode error should have references a log file you can examine for more details. One common issue is that an Android emulator isn't currently running – if you don't already have one running, can you start one by running Android Studio, opening the Device Manager, and starting one of the emulators?

**Comment by ssxray** [comment]
I did have the Android emulator running, but this was a Pixel 2 emulator.  Could that be part of the problem?
Thanks!
Norm

**Comment by aabewhite** [comment]
Not sure - if you post the log as an attachment, we can take a look

**Comment by ssxray** [comment]
Hi Abe,

I’m back on track.  What I had to do to get this to work was the following:

1.	Remove the carriage return after SKIPKEY: so that the license key was on the same line
2.	Upgrade the Android device manager to an API of 32  (it had been on 28).
3.	Remove multiple programs from my Macbook Pro to get enough disk space.

Thanks for your help!

Best regards,

Norm

**Comment by aabewhite** [comment]
Glad you got it working! And thanks for the details. It definitely helps us provide better support in the future.

**Comment by codebrewanshul-cyber** [comment]
Hello @aabewhite @ssxray , I got same issue not able to run app

com.android.ddmlib.InstallException: Unknown failure: Exception occurred while executing 'install':

The gradle command failed. Review the log for details and consult https://skip.dev/docs/faq for common solutions. Command: gradle -p ../Android launchDebug

Execution failed for task ':app:installDebug'.
