### ISSUE TITLE
Kotlin test failed despite being installed

### ISSUE THREAD

**Issue by staticdreams** [skiptools/skip#14]
I have an issue with the HelloSkip base project. I'm unable to compile anything.

``skip doctor`` yields no problems 

```
Skip Doctor
[✓] Skip version 0.7.14 (= 0.7.14)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Check Skip Updates: 0.7.14
[✓] Skip (0.7.14) checks complete
```

however, ``skip checkup`` :

```
[✓] Skip version 0.7.14 (= 0.7.14)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (1.1s)
[✓] Resolve dependencies (10.45s)
[✓] Build hello-skip (14.23s)
[✓] Test Swift (8.97s)
[✗] Test Kotlin (2.57s)
[✓] Archive iOS ipa (16.49s)
[✓] Assemble HelloSkip-release.ipa (0.01s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (0.64s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.14 checkup (55.6s)
Error: 4 errors
```

I have Android Studio installed and I'm having no problems compiling and running apps in it.
Additionally I have downgraded JDK from temurin-21 to openjdk17 as suggested in the other post.
I also installed kotlin on top of Android Studio using ``brew install kotlin`` but to no avail.

Finally, I tried running ``skip checkup --verbose`` to get some insight, but nothing interesting seem to point that there is a problem with Kotlin. The log is huge, so I'm adding it as a separate file if it can help debugging. [skip_checup.txt](https://github.com/skiptools/skip/files/13197728/skip_checup.txt)

Any suggestions?

**Comment by marcprux** [comment]
Looking through the log, I see the line `FAILURE: Build failed with an exception: … No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64` (line 318). I also see on line 1724: `JAVA_HOME=/opt/homebrew/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home`.

Is it possible you have a `JAVE_HOME` environment variable still set? Is so, this will override Skip's local preference for JDK 17. Can you try unsetting it for the skip command with the command: `JAVA_HOME= skip checkup` again?

**Comment by staticdreams** [comment]
If I remove the line I added into my env 
```# export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"```
the original java version goes down to 11, which is not what we want

 Java version 11.0.16.1 (< 17.0.0)

```
skip checkup
[✓] Skip version 0.7.14 (= 0.7.14)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[!] Java version 11.0.16.1 (< 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (1.17s)
[✓] Resolve dependencies (9.96s)
[✓] Build hello-skip (14.45s)
[✓] Test Swift (8.83s)
[✗] Test Kotlin (2.93s)
[✓] Archive iOS ipa (16.33s)
[✓] Assemble HelloSkip-release.ipa (0.01s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (0.64s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.14 checkup (55.45s)
```

**Comment by shial4** [comment]
Same problem here, tried all I could find without success

```
 skip checkup                                
[✓] Skip version 0.7.13 (= 0.7.13)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 21.0.1 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (1.98s)
[✓] Resolve dependencies (18.08s)
[✓] Build hello-skip (36.09s)
[✓] Test Swift (19.63s)
[✗] Test Kotlin (5.34s)
[✓] Archive iOS ipa (28.0s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (1.52s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.13 checkup (112.76s)
Error: 4 errors
```

Error:
```
GRADLE> 
GRADLE> FAILURE: Build failed with an exception.
GRADLE> 
GRADLE> * What went wrong:
GRADLE> Could not determine the dependencies of task ':HelloSkip:testDebugUnitTest'.
GRADLE> > Could not create task ':HelloSkip:compileDebugUnitTestJavaWithJavac'.
GRADLE>    > Failed to calculate the value of task ':HelloSkip:compileDebugUnitTestJavaWithJavac' property 'javaCompiler'.
GRADLE>       > No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific} for MAC_OS on x86_64.
GRADLE>          > No locally installed toolchains match and toolchain download repositories have not been configured.
GRADLE> 
GRADLE> * Try:
GRADLE> > Learn more about toolchain auto-detection at https://docs.gradle.org/8.4/userguide/toolchains.html#sec:auto_detection.
GRADLE> > Learn more about toolchain repositories at https://docs.gradle.org/8.4/userguide/toolchains.html#sub:download_repositories.
GRADLE> > Run with --stacktrace option to get the stack trace.
GRADLE> > Run with --info or --debug option to get more log output.
GRADLE> > Run with --scan to get full insights.
GRADLE> > Get more help at https://help.gradle.org.
GRADLE> 
GRADLE> BUILD FAILED in 2s
[✗] Test Kotlin (4.16s)
```

**Comment by ngnijland** [comment]
I had exactly the same problem before what solved it for me was:

1. Removing all brew cask packages related to android studio and kotling (don't remove the `skip` package)
2. Remove current Java installation following these steps: https://www.java.com/en/download/help/mac_uninstall_java.html
3. Download and install Java from here: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
4. Install Android Studio from here: https://developer.android.com/studio

After doing these things both `skip doctor` and `skip checkup` succeeded. `skip init` succeeded as well and I was able to build to both iOS and Android.

**Comment by staticdreams** [comment]
Intstalling JDK via oracle website (and not via homebrew) did the trick. thanks @ngnijland

**Comment by narendrajagne** [comment]
> > I had exactly the same problem before what solved it for me was:
> > 
> > 1. Removing all brew cask packages related to android studio and kotling (don't remove the `skip` package)
> > 2. Remove current Java installation following these steps: https://www.java.com/en/download/help/mac_uninstall_java.html
> > 3. Download and install Java from here: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
> > 4. Install Android Studio from here: https://developer.android.com/studio
> > 
> > After doing these things both `skip doctor` and `skip checkup` succeeded. `skip init` succeeded as well and I was able to build to both iOS and Android.
> 
> it's work Thank you :-)

% JAVA_HOME= skip checkup          
[✓] Skip version 0.7.15 (= 0.7.15)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0 (= 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 21.0.1 (> 17.0.0)
[⢇] Android Studio version[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (0.87s)
[✓] Resolve dependencies (23.2s)
[✓] Build hello-skip (29.2s)
[✓] Test Swift (17.97s)
[✓] Test Kotlin (581.59s)
[✓] Archive iOS ipa (39.64s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✓] Assembling Android apk (208.78s)
[✓] Verify HelloSkip-release.apk 9.5 MB
[✓] Skip 0.7.15 checkup (902.79s)

**Comment by naticio** [comment]
I did all, this 
brew uninstall --cask android-platform-tools
remove java
install jdk17

and still didn't work. I am also using the simulator for some react native work, might be conflicting?

**Comment by mmmago** [comment]
@marcprux I now also have issue with Kotlin failing in `skip checkup `.

<img width="888" alt="Capture d’écran 2024-05-27 à 11 18 37" src="https://github.com/skiptools/skip/assets/76073612/c477e2bb-4d1e-42b4-84c6-cdffaeac8e8a">

[skip-checkup-2024-05-27T09:15:04Z.txt](https://github.com/skiptools/skip/files/15453760/skip-checkup-2024-05-27T09.15.04Z.txt)



> I had exactly the same problem before what solved it for me was:
> 
>     1. Removing all brew cask packages related to android studio and kotling (don't remove the `skip` package)
> 
>     2. Remove current Java installation following these steps: https://www.java.com/en/download/help/mac_uninstall_java.html
> 
>     3. Download and install Java from here: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
> 
>     4. Install Android Studio from here: https://developer.android.com/studio
> 
> 
> After doing these things both `skip doctor` and `skip checkup` succeeded. `skip init` succeeded as well and I was able to build to both iOS and Android.



> I had exactly the same problem before what solved it for me was:
> 
>     1. Removing all brew cask packages related to android studio and kotling (don't remove the `skip` package)
> 
>     2. Remove current Java installation following these steps: https://www.java.com/en/download/help/mac_uninstall_java.html
> 
>     3. Download and install Java from here: https://www.oracle.com/java/technologies/downloads/#jdk17-mac
> 
>     4. Install Android Studio from here: https://developer.android.com/studio
> 
> 
> After doing these things both `skip doctor` and `skip checkup` succeeded. `skip init` succeeded as well and I was able to build to both iOS and Android.

This is not helping, as there is nothing anymore in `opt/homebrew/opt/java` when installing from oracle website and not from homebrew.

**Comment by mmmago** [comment]
> This issue seems to be different than the others. The relevant error from the log file appears to be:
> 
> > Timeout waiting to lock journal cache (/Users/lucas/.gradle/caches/journal-1). It is currently in use by another Gradle instance.
> > Owner PID: 54106
> > Our PID: 69242
> > Owner Operation:
> > Our operation:
> > Lock file: /Users/lucas/.gradle/caches/journal-1/journal-1.lock
> 
> I haven't seen this before, but you might be able to get past it by simply killing the Gradle daemon with the Terminal command `killall java` and then trying to run the command again.
> 
> Let us know if this helps. If not, we can keep digging.

Thanks for the fast troubleshoot. `killall java` returned an error, but now it looks like `skip checkup` sucessfully pass everything !

I'll go through the process of porting my iOS app without knowing anything about android now :^) Thanks for your help !
