### ISSUE TITLE
licence key not found error

### ISSUE THREAD

**Issue by algoscienceacademy** [skiptools/skip#152]
![image](https://github.com/skiptools/skip/assets/76747815/07967b1b-b754-469c-9c37-ac11f1126d1c)
![image](https://github.com/skiptools/skip/assets/76747815/a10b0dfa-6a3a-44ba-aab8-ffde28d5222e)

**Comment by marcprux** [comment]
I think you need a space between "SKIPKEY:" and the actual license key in the skipkey.env file.

**Comment by algoscienceacademy** [comment]
Problem solve thank you
