### ISSUE TITLE
Error Setting Up for the frist time

### ISSUE THREAD

**Issue by danielcr12** [skiptools/skip#153]
I just installed from brew and ran the checkup command, all seem to be fine and ready fro me to start,  all test are passing, but when I create the hello skip to build the frist app and start woking, the gladle script that is uncharge of triggering the android counterpart seems to be broken and I can get Xcode to run the android app, I always get a word error message about the JAVA_HOME pay not being set or something but the terminal and the checkup system seem to weak, is im a bit lost on how to set this up.

this is the cradle scrip you can find it in the build phases for your target project, this is just the hello skip app, if omit this scrip Xcode does build the app but only for iOS:

 if [ "${SKIP_ZERO}" != "" ]; then
    echo "note: skipping skip due to SKIP_ZERO"
    exit 0
fi

if [ "${ENABLE_PREVIEWS}" == "YES" ]; then
    echo "note: skipping skip due to ENABLE_PREVIEWS"
    exit 0
fi

if [ "${ACTION}" = "install" ]; then
    SKIP_ACTION="build"
else
    SKIP_ACTION="${SKIP_ACTION:-launch}"
fi

# Print other critical environment variables
echo "BUILD_ROOT is set to: $BUILD_ROOT"
echo "HOMEBREW_PREFIX is set to: ${HOMEBREW_PREFIX:-/opt/homebrew}"

# Update PATH
PATH=${BUILD_ROOT}/Debug:${BUILD_ROOT}/../../SourcePackages/artifacts/skip/skip/skip.artifactbundle/macos:${PATH}:${HOMEBREW_PREFIX:-/opt/homebrew}/bin

# Print PATH to debug
echo "PATH is set to: $PATH"

# Run the command
echo "note: running gradle build with: $(which skip) gradle -p ${PWD}/../Android ${SKIP_ACTION:-launch}${CONFIGURATION:-Debug}"
skip gradle -p ../Android ${SKIP_ACTION:-launch}${CONFIGURATION:-Debug}

danielcarrero@Daniels-MacBook-Air ~ % skip checkup
[✓] Skip version 0.8.51 (= 0.8.51)
[✓] macOS version 14.5 (> 13.5.0)
[✓] Swift version 5.10 (> 5.9.0)
[✓] Xcode version 15.4 (> 15.0.0)
[✓] Xcode tools SDKs: 7
[✓] Homebrew version 4.3.6 (> 4.1.0)
[✓] Gradle version 8.8 (> 8.6.0)
[✓] Java version 22.0.1 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2024.1
[✓] Android tools SDKs: 2
[✓] Resolve dependencies (26.79s)
[✓] Build hello-skip (22.66s)
[✓] Test Swift (15.1s)
[✓] Test Kotlin (170.38s)
[✓] Archive iOS ipa (95.91s)
[✓] Assemble HelloSkip-release.ipa 37 KB
[✓] Verify HelloSkip-release.ipa 37 KB
[✓] Assembling Android apk (337.95s)
[✓] Verify HelloSkip-release.apk 12.7 MB
[✓] Check Swift Package (34.57s)
[✓] Skip 0.8.51 checkup succeeded in 709.69s
danielcarrero@Daniels-MacBook-Air ~ %

**Comment by marcprux** [comment]
Sorry for the trouble. When the build fails, there should be a Gradle log that Xcode references in the build errors. Can you post that log here so we can see the actual error message?

Also, can you open Terminal and post the output of the `env` command, as well as `java -version` and `which java`? Problems like this usually have something to do with a different Java overriding the one that our tools expect, so sometimes it is just a matter of removing any `JAVA_HOME` setting you may have set in your environment file (`~/.zshrc`).

**Comment by danielcr12** [comment]
this is all that is shown in the log:
**
ERROR: JAVA_HOME is set to an invalid directory: /opt/homebrew/opt/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
**

ENV
Last login: Sat Jun 22 14:36:00 on ttys000
danielcarrero@Daniels-MacBook-Air ~ % env
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/q3/6k1dbsc96ng5q7nyr4jgwk6h0000gp/T/
XPC_FLAGS=0x0
LaunchInstanceID=0BC3287E-63C4-4A21-A93B-4792153E9BFB
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.plMYHGQVvl/Listeners
SECURITYSESSIONID=186b3
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=453
TERM_SESSION_ID=3F884C07-3348-4D02-A65E-9FE9879D4C1C
SHELL=/bin/zsh
HOME=/Users/danielcarrero
LOGNAME=danielcarrero
USER=danielcarrero
PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
SHLVL=1
PWD=/Users/danielcarrero
OLDPWD=/Users/danielcarrero
LC_CTYPE=UTF-8
_=/usr/bin/env
danielcarrero@Daniels-MacBook-Air ~ % 

JAVA VERSION
Danielcarrero@Daniels-MacBook-Air ~ % java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

WICH JAVA
danielcarrero@Daniels-MacBook-Air ~ % which java  
/usr/bin/java

danielcarrero@Daniels-MacBook-Air ~ % ~/.zshrc
zsh: no such file or directory: /Users/danielcarrero/.zshrc

this from the terminal:
danielcarrero@Daniels-MacBook-Air ~ % skip checkup
[✓] Skip version 0.8.51 (= 0.8.51)
[✓] macOS version 14.5 (> 13.5.0)
[✓] Swift version 5.10 (> 5.9.0)
[✓] Xcode version 15.4 (> 15.0.0)
[✓] Xcode tools SDKs: 7
[✓] Homebrew version 4.3.6 (> 4.1.0)
[✓] Gradle version 8.8 (> 8.6.0)
[✓] Java version 22.0.1 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2024.1
[✓] Android tools SDKs: 2
[✓] Resolve dependencies (24.61s)
[✓] Build hello-skip (49.62s)
[✓] Test Swift (32.98s)
[✓] Test Kotlin (210.99s)
[✓] Archive iOS ipa (133.58s)
[✓] Assemble HelloSkip-release.ipa 37 KB
[✓] Verify HelloSkip-release.ipa 37 KB
[✗] Assembling Android apk (289.03s)
[✗] Verify HelloSkip-release.apk: The file “app-release-unsigned.apk” couldn’t be opened because there is no such file.
[✓] Check Swift Package (2.11s)
[✗] Skip 0.8.51 checkup failed with 2 errors
Output logged to: /tmp/skip-checkup-2024-06-22T08:11:13Z.txt
See https://skip.tools/docs/faq and https://community.skip.tools for help
Error: 3 errors

[skip-checkup-2024-06-22T08:11:13Z.txt](https://github.com/user-attachments/files/15935819/skip-checkup-2024-06-22T08.11.13Z.txt)

**Comment by marcprux** [comment]
Can you try upgrading to skip 0.8.54 (by running "brew update" and then "brew upgrade skip"), and then creating a new project (e.g., `skip init --open-xcode --appid=my.bundle.id MyApp my-app`) and trying to build again? We've made a couple of fixes that may help address the issue.

If it still fails, please again send the log.

**Comment by danielcr12** [comment]
now for some reason creating a new project just fails: danielcarrero@Daniels-MacBook-Air ~ % skip init --open-xcode --appid=pet.carekrakenr PetCare+ Pet-Care
Initializing Skip application PetCare+
[✓] Resolve dependencies (80.11s)
[✗] Build PetCare+ (207.22s)
[✓] Check Swift Package (1.0s)
[✓] Created module Pet-Care in /Users/danielcarrero/PetCare+
[✓] Opening Xcode project (0.9s)
[✗] Skip 0.8.54 init failed with 1 error
Output logged to: /tmp/skip-init-2024-06-22T17:13:57Z.txt
See https://skip.tools/docs/faq and https://community.skip.tools for help
Error: 2 errors
danielcarrero@Daniels-MacBook-Air ~ % 
[skip-init-2024-06-22T17:13:57Z.txt](https://github.com/user-attachments/files/15937567/skip-init-2024-06-22T17.13.57Z.txt)

**Comment by danielcr12** [comment]
managed to get all check when creating a project however im still facing the same problem when it comes to building for both targets, the issue only happens when also building for android:

this is the griddle error:

ERROR: JAVA_HOME is set to an invalid directory: /opt/homebrew/opt/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

if I only run the script for install build I can compile and run for iOS but not android, also the skip checkup and skip doctor commands all run with no problems and give full green marks

![Uploading Screenshot 2567-06-23 at 00.29.07.png…]()

**Comment by marcprux** [comment]
Can you open Terminal and check whether `/opt/homebrew/opt/java` exists? That should be where Homebrew installs the OpenJDK link.

Also, can you run `java -version` and `env` and post the output?

And please confirm that `skip checkup` is still passing with the latest version of skip. And perhaps restart Xcode to see if that helps.

**Comment by danielcr12** [comment]
danielcarrero@Daniels-MacBook-Air ~ % cd /opt/homebrew/opt/java

cd: no such file or directory: /opt/homebrew/opt/java

danielcarrero@Daniels-MacBook-Air ~ % java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)


danielcarrero@Daniels-MacBook-Air ~ % env
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/q3/6k1dbsc96ng5q7nyr4jgwk6h0000gp/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.uaE61IMeF4/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=453
TERM_SESSION_ID=564D9D35-DB54-42B5-8C65-36D1B87B5585
SHELL=/bin/zsh
HOME=/Users/danielcarrero
LOGNAME=danielcarrero
USER=danielcarrero
PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
SHLVL=1
PWD=/Users/danielcarrero
OLDPWD=/Users/danielcarrero
LC_CTYPE=UTF-8
_=/usr/bin/env



danielcarrero@Daniels-MacBook-Air ~ % skip checkup 
[✓] Skip version 0.8.54 (= 0.8.54)
[✓] macOS version 14.5 (> 13.5.0)
[✓] Swift version 5.10 (> 5.9.0)
[✓] Xcode version 15.4 (> 15.0.0)
[✓] Xcode tools SDKs: 7
[✓] Homebrew version 4.3.6 (> 4.1.0)
[✓] Gradle version 8.8 (> 8.6.0)
[✓] Java version 22.0.1 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2024.1
[✓] Android tools SDKs: 2
[✓] Resolve dependencies (40.91s)
[✓] Build hello-skip (81.53s)
[✓] Test Swift (42.98s)
[✓] Test Kotlin (585.92s)
[✓] Archive iOS ipa (130.2s)
[✓] Assemble HelloSkip-release.ipa 37 KB
[✓] Verify HelloSkip-release.ipa 37 KB
[✓] Assembling Android apk (671.14s)
[✓] Verify HelloSkip-release.apk 12.8 MB
[✓] Check Swift Package (23.96s)
[✓] Skip 0.8.54 checkup succeeded in 1609.02s
danielcarrero@Daniels-MacBook-Air ~ %

**Comment by danielcr12** [comment]
this is shown in Xcode: /Users/danielcarrero/Library/Developer/Xcode/DerivedData/HelloSkip-exetzgcnvjcemveveytswyvbltzp/Build/Intermediates.noindex/HelloSkip.build/Debug-iphoneos/HelloSkip.build/skip-gradle.log.txt:6:1 The gradle command failed. Review the log for details and consult https://skip.tools/docs/faq for common solutions. Command: gradle -p ../Android launchDebug


ERROR: JAVA_HOME is set to an invalid directory: /opt/homebrew/opt/java

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by danielcr12** [comment]
also when reinstalling idk I get this iso I think Mac is using a different install link for idk: 

For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

openjdk is keg-only, which means it was not symlinked into /usr/local,
because macOS provides similar software and installing this software in
parallel can cause all kinds of trouble.

If you need to have openjdk first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/usr/local/opt/openjdk/include"
==> Summary
🍺  /usr/local/Cellar/openjdk/22.0.1: 601 files, 327.9MB
==> Running `brew cleanup openjdk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
danielcarrero@Daniels-MacBook-Air ~ %

**Comment by marcprux** [comment]
Are you on an Intel mac or ARM? Or, perchance, did you upgrade and migrate your system from an Intel to an ARM mac with a previous Homebrew installation? That has been known to cause problems because the Gradle build doesn't play well with Rosetta translation. The solution, in that case, has been to remove and re-install [Homebrew](https://brew.sh) and then re-install Skip.

If that isn't the issue, please let us know and we will continue to dig.

**Comment by danielcr12** [comment]
following this commands fixed it for me I can now compile:

sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc

export CPPFLAGS="-I/usr/local/opt/openjdk/include"

**Comment by marcprux** [comment]
Nice job! Glad you got it working, but none of that should have been necessary. I'm curious about what is different on your system than on other systems that work out of the box. Did you have a prior version of Java already installed on your machine before you installed Skip? Also, was the `export CPPFLAGS` environment variable necessary, and if so, what was the problem that was exhibited when you didn't have it set?

Thanks for your patience and fortitude in getting this working, and please do let us know if you encounter future issues. We are working hard to try to maximize the out-of-the-box compatibility with Skip and common macOS setups.

**Comment by danielcr12** [comment]
Yes, after checking my setup I found 6 Java versions and I had to force
unistall everything ans reinstall from scratch, I also applied the commands
just to be safe,

**Comment by marcprux** [comment]
> found 6 Java versions

That might be a record!

I'll close this issue, but please don't hesitate to open a new one if you encounter any further problems.
