### ISSUE TITLE
Missing .frame(maxWidth: Double.infinity)

### ISSUE THREAD

**Issue by shial4** [skiptools/skip#17]
![Screenshot 2023-10-30 at 19 42 39](https://github.com/skiptools/skip/assets/8544773/aca2e5b8-3a60-4356-bdb2-1e0bb1f3c950)

**Comment by marcprux** [comment]
This is the expected error when we haven't yet implemented an API.

An overview of the currently support SwiftUI can be found at https://skip.tools/docs/modules/skip-ui/#supported-swiftui
