### ISSUE TITLE
Error while setup/installation 

### ISSUE THREAD

**Issue by narendrajagne** [skiptools/skip#18]
skip checkup                    
[✓] Skip version 0.7.15 (= 0.7.15)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0 (= 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✗] Gradle version: error executing gradle
[✓] Java version 21.0.1 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (0.94s)
[✓] Resolve dependencies (22.78s)
[✓] Build hello-skip (27.78s)
[✓] Test Swift (16.39s)
[✗] Test Kotlin (1.48s)
[✓] Archive iOS ipa (35.66s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (0.01s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.15 checkup (106.03s)

but while use 
JAVA_HOME= skip checkup
[✓] Skip version 0.7.15 (= 0.7.15)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0 (= 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 21.0.1 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (0.93s)
[✓] Resolve dependencies (23.83s)
[✓] Build hello-skip (25.94s)
[✓] Test Swift (16.07s)
[✗] Test Kotlin (5.51s)
[✓] Archive iOS ipa (34.92s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (1.28s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.15 checkup (109.95s)

**Comment by phoenix-error** [comment]
I have the same problem...

**Comment by narendrajagne** [comment]
it resolved now
JAVA_HOME= skip checkup          
[✓] Skip version 0.7.15 (= 0.7.15)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0 (= 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 21.0.1 (> 17.0.0)
[⢇] Android Studio version[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (0.87s)
[✓] Resolve dependencies (23.2s)
[✓] Build hello-skip (29.2s)
[✓] Test Swift (17.97s)
[✓] Test Kotlin (581.59s)
[✓] Archive iOS ipa (39.64s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✓] Assembling Android apk (208.78s)
[✓] Verify HelloSkip-release.apk 9.5 MB
[✓] Skip 0.7.15 checkup (902.79s)

**Comment by narendrajagne** [comment]
> I have the same problem...

follow this steps and reinstall it 
https://www.java.com/en/download/help/mac_uninstall_java.html

**Comment by Mcrich23** [comment]
Same issue, nothing suggested has worked for me

**Comment by Mcrich23** [comment]
@marcprux @aabewhite Any ideas?

**Comment by lexonerus** [comment]
Same Issue.
Intel Mac mini 2018

Skip doctor works fine
```
Skip Doctor
[✓] Skip version 0.7.16 (= 0.7.16)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.18 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Check Skip Updates: 0.7.16
[✓] Skip (0.7.16) checks complete
```
But checkup make attention to Kotlin test
```
[✓] Skip version 0.7.16 (= 0.7.16)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.18 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (5.06s)
[✓] Resolve dependencies (18.22s)
[✓] Build hello-skip (45.23s)
[✓] Test Swift (19.59s)
[✗] Test Kotlin (28.74s)
[✓] Archive iOS ipa (35.74s)
[✓] Assemble HelloSkip-release.ipa (0.03s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✗] Assembling Android apk (4.73s)
[✗] Verify HelloSkip-release.apk: The file “HelloSkip-release-unsigned.apk” couldn’t be opened because there is no such file.
[✗] Skip 0.7.16 checkup (158.55s)
Error: 4 errors
```

I reinstalled Android Studio using brew, reinstalled java and kotlin, nothing helps.
@narendrajagne how do you resolved this?

**Comment by keetsta** [comment]
same issue

**Comment by aabewhite** [comment]
@james-mcdougall What is the output of:
xcode-select -p

**Comment by james-mcdougall** [comment]
@aabewhite 

➜  ~ xcode-select -p
/Library/Developer/CommandLineTools

So I am assuming I need possibly to redownload my command line tools? Xcode builds any previous projects just fine. I have deleted previous derived data. Thoughts?

**Comment by aabewhite** [comment]
> @aabewhite
> 
> ➜ ~ xcode-select -p /Library/Developer/CommandLineTools
> 
> So I am assuming I need possibly to redownload my command line tools? Xcode builds any previous projects just fine. I have deleted previous derived data. Thoughts?

You just need to point xcode-select at Xcode rather than at CommandLineTools. 
xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by cannyboy** [comment]
> * JAVA_HOME must be exported to the path of openjdk 17

What is the path? Or, how to find?

**Comment by Mcrich23** [comment]
M1 Mac path: /opt/homebrew/Cellar and then find the right folder

**Comment by andresantana-dev** [comment]
Still having the same issue, any idea how to fix it? (failing Test Kotlin, Assembling Android apk)

**Comment by james-mcdougall** [comment]
@aabewhite

That definitely worked! Thanks so much!

**Comment by PAVUNRAJ** [comment]
Hi folks,
I facing creating a issue 

[✓] Skip version 0.7.19 (= 0.7.19)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✗] Xcode version: error executing xcodebuild
[✓] Homebrew version 4.1.18 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✗] Create project hello-skip (0.06s)

**Comment by james-mcdougall** [comment]
@PAVUNRAJ

Read the thread, I had this same issue and @aabewhite answered my question and helped me fix the issue.

**Comment by andresantana-dev** [comment]
![image](https://github.com/skiptools/skip/assets/70408586/d1f6fc86-1573-40c9-ab78-18998e169192)

echo JAVA_HOME
![image](https://github.com/skiptools/skip/assets/70408586/8d9e04e7-7ab0-424c-86e7-8680db85c88a)

Still failing Test Kotlin, any help? please

**Comment by PAVUNRAJ** [comment]
Hi @aabewhite, I tried another command, and it's working fine for me.
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by PAVUNRAJ** [comment]
> @PAVUNRAJ
> 
> Read the thread, I had this same issue and @aabewhite answered my question and helped me fix the issue.

thanks for your answer

**Comment by marcprux** [comment]
It sounds like this issue is resolved for most people by using `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`. Please re-open the issue if it persists. We will add some extra logic to `skip doctor` to advise on the need to update the Xcode location when this happens.

**Comment by james-mcdougall** [comment]
@andresantana-dev 

You have to download the latest version of Android Studio and actually run the simulator once for it to register everything. Once you do that, do another Skip Checkup and everything should work. That is what I did and it resolved that same issue for me.

**Comment by andresantana-dev** [comment]
> @andresantana-dev
> 
> You have to download the latest version of Android Studio and actually run the simulator once for it to register everything. Once you do that, do another Skip Checkup and everything should work. That is what I did and it resolved that same issue for me.

I have the latest Android Studio version, but keeps failing the Test Kotlin.

Thank so much for your help!

**Comment by aabewhite** [comment]
@andresantana-dev Sorry, I may be missing some context. Can you please post the complete output? You also might try running with the -v option to see if that sheds any light on the error.

**Comment by andresantana-dev** [comment]
@aabewhite GRADLE> Starting a Gradle Daemon (subsequent builds will be faster)
GRADLE> Checking the license for package Android SDK Build-Tools 33.0.1 in /Users/santana/Library/Android/sdk/licenses
GRADLE> Warning: License for package Android SDK Build-Tools 33.0.1 not accepted.
GRADLE> Checking the license for package Android SDK Platform 34 in /Users/santana/Library/Android/sdk/licenses
GRADLE> 
GRADLE> Warning: License for package Android SDK Platform 34 not accepted.
GRADLE> 
GRADLE> 
GRADLE> * What went wrong:
GRADLE> Could not determine the dependencies of task ':HelloSkip:testDebugUnitTest'.
GRADLE> > Failed to install the following Android SDK packages as some licences have not been accepted.
GRADLE>      build-tools;33.0.1 Android SDK Build-Tools 33.0.1
GRADLE>      platforms;android-34 Android SDK Platform 34
GRADLE>   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
GRADLE>   All licenses can be accepted using the sdkmanager command line tool:
GRADLE>   sdkmanager.bat --licenses
GRADLE>   Or, to transfer the license agreements from one workstation to another, see https://developer.android.com/studio/intro/update.html#download-with-gradle
GRADLE>   
GRADLE>   Using Android SDK: /Users/santana/Library/Android/sdk
GRADLE> 
GRADLE> * Try:
GRADLE> > Run with --stacktrace option to get the stack trace.
GRADLE> > Run with --info or --debug option to get more log output.
GRADLE> > Run with --scan to get full insights.
GRADLE> > Get more help at https://help.gradle.org.
GRADLE> 
GRADLE> BUILD FAILED in 14s
[✗] Test Kotlin (16.11s)

Thanks for the message, with the -v option I'm getting a lot more information

**Comment by naticio** [comment]
did you fix it? I have the same issue in the same step 
[✗] Assembling Android apk (16.52s)
[✗] Verify HelloSkip-release.apk: /var/folders/9_/xqn4bxx955z6npf3wh5n74nw0000gn/T//03BC17E4-60FB-4893-B9F9-17D333D9B369/hello-skip/.build/Android/app/outputs/apk/release/app-release-unsigned.apk: The file “app-release-unsigned.apk” couldn’t be opened because there is no such file.
[✓] Check Swift Package (0.44s)
[✗] Skip 0.8.2 checkup (119.35s)

**Comment by aabewhite** [comment]
Nat, can you please post (or email us) the result of running the command with the -v option to get verbose output? 

Thanks!

**Comment by naticio** [comment]
sure, here it is
[skip log.txt](https://github.com/skiptools/skip/files/14188290/skip.log.txt)

**Comment by marcprux** [comment]
It looks like you still had skip 0.8.2 (which exhibited this problem), and that the upgrade to 0.8.4 didn't take place. We've seen a couple of other reports of this … can you try first running `brew update` and then `brew upgrade skip`, and then run `skip checkup` and make sure that it is 0.8.4 running?

**Comment by naticio** [comment]
that worked, thanks!
basically the skip upgrade couldn't upgrade for some reason, then I updated brew and skip via brew and it worked. thanks!
