### ISSUE TITLE
SkipDriveExternal.ProcessResult.Error error 0

### ISSUE THREAD

**Issue by narendrajagne** [skiptools/skip#19]
The operation couldn’t be completed. (SkipDriveExternal.ProcessResult.Error error 0.)

**Comment by idineshgovind** [comment]
I'm also facing the same

**Comment by marcprux** [comment]
That's a general error when something goes wrong. For the time being, the only way to get more information is to go to the Report Navigator and select the failing build, and expand it to see the Gradle output. For example:

<img width="1187" alt="Screenshot 2023-11-06 at 13 36 52" src="https://github.com/skiptools/skip/assets/659086/aea27830-2527-4603-b222-8740410cadc9">

You can copy and log output to the clipboard and paste it into this issue, and we can try to help identify the cause. Please re-open this issue if you have further information.
