### ISSUE TITLE
The file “Payload” doesn’t exist Issue

### ISSUE THREAD

**Issue by xtor007** [skiptools/skip#20]
<img width="355" alt="Screenshot 2023-10-30 at 16 54 42" src="https://github.com/skiptools/skip/assets/71408259/d909dcdd-e9f0-4d34-8c57-5a2be6b096cf">
There is a problem when running skip checkup, Java has already been updated to the latest version.
MacBook Pro 2021 M1, Sonoma 14.0

**Comment by marcprux** [comment]
Try running `skip upgrade` to Skip 0.7.16 and see if it helps. If not, can you run `skip checkup -v` to see where the error is occurring?

**Comment by marcprux** [comment]
Please re-open with the output of `skip checkup -v` if the problem persists.

**Comment by cannyboy** [comment]
I have a similar `skip checkup` output as @xtor007 , except my Kotlin gets a tick.

```
$ 
[✓] Skip version 0.7.21 (= 0.7.21)
[✓] macOS version 14.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.19 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Create project hello-skip (2.24s)
[✓] Resolve dependencies (22.09s)
[✓] Build hello-skip (95.26s)
[✓] Test Swift (68.47s)
[✓] Test Kotlin (176.88s)
[✗] Archive iOS ipa (18.5s)
Error: The file “Payload” doesn’t exist.
```

I think `Archive iOS` issue is when you haven't downloaded the latest simulator (7GB!) after launching Xcode. Downloading now...
