### ISSUE TITLE
`RoundedBorderTextFieldStyle` works for iOS but not Android

### ISSUE THREAD

**Issue by mchampanis** [skiptools/skip#219]
I'm trying skip out, and my sample app won't transpile for Android:

```swift
TextField("Enter a number", text: $num)
    .keyboardType(.decimalPad)
    .textFieldStyle(RoundedBorderTextFieldStyle())
    .padding()
```

```gradle
> Task :skipstone:Freefall2:compileDebugKotlin FAILED
e: .../src/main/kotlin/freefall2/module/ContentView.kt:41:41 Unresolved reference 'RoundedBorderTextFieldStyle'.
```

What is the best way to tackle this? How and where would I add support for `RoundedBorderTextFieldStyle` to skip's codebase?

I am currently working around it with `#if SKIP` and `ComposeView`.

**Comment by aabewhite** [comment]
Is this a custom TextFieldStyle, or are you trying to use the built-in rounded border style? If the latter, `.textFieldStyle(.roundedBorder)` works across platforms.

**Comment by aabewhite** [comment]
Oh wow, I didn't realize it was deprecated. I'll make a note to move Skip to supporting the style objects directly. Thanks!

**Comment by aabewhite** [comment]
I looked into this, and I don't think .roundedBorder is actually deprecated. Maybe it was an error in the beta referenced in the StackOverflow question.
