### ISSUE TITLE
Add skip exist project.

### ISSUE THREAD

**Issue by alphaSoft99** [skiptools/skip#23]
How i can add skip in my exist ios project. I can't found any documentation

**Comment by marcprux** [comment]
Skip is designed more for greenfield app projects, at least during the current tech preview state. While it might be possible to adapt an existing app's project to Skip manually, we generally recommend starting with `skip init --appid=com.xyz.App SomeProject SomeModuleA SomeModuleB`. For an existing app that relies on SPM, you can migrate the code into the various modules you created with the app, and then use the `SomeProject.xcodeproj` created by `skip` to build and run the app in iOS and Android.

We will close this issue for now, but feel free to re-open if we can provide further guidance.
