### ISSUE TITLE
Skip.env not took into account

### ISSUE THREAD

**Issue by qeude** [skiptools/skip#268]
Hello!

I'm playing a bit with Skip and trying to make a call to an external API. To do so I tried storing the needed keys and urls in the `Skip.env` file, but for some reason, nothing is then added to `xcconfig` nor `Info.plist` and the app just crashes.

I basically just added something like this to the `Skip.env` and reading to the documentation I would expect it to just work.

```
MY_API_URL = https://api.url.com
MY_API_KEY = temporestlaborumdonostrudullamcopariaturelitexercitationofficiaea
```

Am I missing something?

Thanks!

**Comment by marcprux** [comment]
`Skip.env` does not transmit general metadata through to the app – rather, it is for a pre-defined set of build metadata (like the `MARKETING_VERSION`) that will be converted to both the Info.plist (on the iOS side) and AndroidManifest.xml (on the Android side) on a case-by-case basis.

For providing runtime metadata for your app, we generally recommend putting it in a JSON file in the `Resources/` folder, and then decoding it at runtime.

**Comment by qeude** [comment]
@marcprux thanks for the quick answer!

Storing this kind of information in a plain json file doesn't make it a bit more "dangerous" since it could be accessed from decompiling the `.ipa` or the `.apk` in an easier way?

**Comment by marcprux** [comment]
Whether it is embedded in an `Info.plist` or `Info.json`, any metadata you include with your app's binary itself should be considered publicly-accessible for all intents and purposes, including embedding it in the compiled code itself. Some mechanisms may be marginally more difficult to reverse-engineer, but ultimately storing secret information (like API or encryption keys) inside an app's bundle is generally considered unsafe.
