### ISSUE TITLE
Fails to build project in Xcode 16

### ISSUE THREAD

**Issue by rafaelnobrekz** [skiptools/skip#275]
Hello! Thanks for such an awesome tool. I'm evaluating Skip on a new side project, and while I'm able to build & run the project on Xcode 15.4.0, it does not compile on Xcode 16 with the following error:

```
Cycle in dependencies between targets 'SideProject' and 'SideProjectApp'; building could produce unreliable results.
Cycle path: SideProject → SideProjectApp → SideProject
Cycle details:
→ Target 'SideProject' has an explicit dependency on Target 'SideProjectApp'
→ Target 'SideProjectApp' has an explicit dependency on Target 'SideProject'
```

Is this a known issue? Any workarounds so far?

Thank you,
Rafael

**Comment by aabewhite** [comment]
I think this is just a naming issue. What arguments did you supply to "skip init" when you created the project?

**Comment by rafaelnobrekz** [comment]
Hmm. It was `skip init --open-xcode --appid=com.mycompany.SideProject sideproject SideProject`
Could the case-only difference in the argument values above be the culprit ?

**Comment by rafaelnobrekz** [comment]
Okay, recreating with different names does work well on Xcode 16, thank you!
