### ISSUE TITLE
Using #colorLiteral() throws a compiler error when using #if !SKIP

### ISSUE THREAD

**Issue by lexum0** [skiptools/skip#304]
Using the #colorLiteral() macro inside a #if !SKIP block throws the error `Skip does not support this Swift macro`.

Skip should not throw an error on code that is meant for iOS only

**Comment by lexum0** [comment]
It looks like it works as expected. The problem is Skip throws errors that it shouldn't like this one and it's hard to know which errors are real and what code should be changed

**Comment by aabewhite** [comment]
I was not able to reproduce an error when using #colorLiteral within a #if !SKIP block.

I have, however, gone ahead and added #colorLiteral support. It'll land some time in the next day or two

**Comment by lexum0** [comment]
Awesome, thank you!

Could you add support for the #warning() macro? Even if it's something simple so it doesn't need an #if !SKIP block. Thanks

**Comment by aabewhite** [comment]
Done. They'll just turn into a comment on the Android side, and the Xcode iOS build will continue to surface them as warnings/errors

**Comment by lexum0** [comment]
Thank you!
