### ISSUE TITLE
How to use it in an existing project?

### ISSUE THREAD

**Issue by rantianhua** [skiptools/skip#42]

**Comment by marcprux** [comment]
At this point in Skip's development, we don't have a good solution for taking an existing project and "Skipifying" it.

For the time being, we recommend creating a new app or framework project with `skip init` (see https://skip.tools/docs/gettingstarted/) and getting that running, and then migrating your existing app over piecemeal. This might be as simple as copying the individual `.swift` files into the new project's `Sources/AppName/` folder.
