### ISSUE TITLE
How To Retrofit my Existing App to Skip

### ISSUE THREAD

**Issue by davidakoontz** [skiptools/skip#53]
### Discussed in https://github.com/skiptools/skip/discussions/52

<div type='discussions-op-text'>

<sup>Originally posted by **davidakoontz** November 20, 2023</sup>
Let's go beyond the Hello World (Skippers) App...  By what general process would I start moving my existing app into a ... skip framework? 

Step 1:  Do I start from a blank project in Xcode?  OR - (my best guess) start from the Hello-Skip app with the structure and working code.

Step 2:  What can I file-copy over to the new (renamed - yeah how?) Hello-Skip app that has other dependencies...?  I guess at some point it requires everything be copied.

Step 3:  So then I try to compile in Xcode... and it kicks in the SkipStone Transpiler...  something is going to break...  What's the general guidance for fixing / ignoring / redesigning...

Surely you have more advice to give along this topic...

What to do first...

What to do last or much later...

What is not (YET) going to work...

For example - SF Symbols... Colors...  Fonts... etc.

Maybe you could explain the deeper meaning behind your Module meaning.  e.g. "Skip is designed to accommodate and encourage using multi-module projects."  I'm just a simple App builder... no modules required.  What might I benefit from?

</div>

As they have not yet written but one page of Documentations ... maybe we first adopters are going to have to blaze this trail.
-- David

**Comment by marcprux** [comment]
This was responded to in the discussion at https://github.com/skiptools/skip/discussions/52, so I'll close this and the thread can be continued there.
