### ISSUE TITLE
How To Retrofit my Existing App to Skip

### ISSUE THREAD

**Issue by davidakoontz** [skiptools/skip#54]
### Discussed in https://github.com/skiptools/skip/discussions/52

<div type='discussions-op-text'>

<sup>Originally posted by **davidakoontz** November 20, 2023</sup>
Let's go beyond the Hello World (Skippers) App...  By what general process would I start moving my existing app into a ... skip framework? 

Step 1:  Do I start from a blank project in Xcode?  OR - (my best guess) start from the Hello-Skip app with the structure and working code.

Step 2:  What can I file-copy over to the new (renamed - yeah how?) Hello-Skip app that has other dependencies...?  I guess at some point it requires everything be copied.

Step 3:  So then I try to compile in Xcode... and it kicks in the SkipStone Transpiler...  something is going to break...  What's the general guidance for fixing / ignoring / redesigning...

Surely you have more advice to give along this topic...

What to do first...

What to do last or much later...

What is not (YET) going to work...

For example - SF Symbols... Colors...  Fonts... etc.

Maybe you could explain the deeper meaning behind your Module meaning.  e.g. "Skip is designed to accommodate and encourage using multi-module projects."  I'm just a simple App builder... no modules required.  What might I benefit from?

</div>

**Comment by davidakoontz** [comment]
OK - I'm giving in and asking...

I added a Swift View file into the HelloSkip project and tried to compile.  It failed.... the Canvas preview message states it cannot compile because the file is not in the scheme...  OMG!  What does that mean... well the internet thinks it means to restart Xcode.

Then I took a closer look at the HelloSkip project - there is yet-another logical place to put a new file... so I moved it... same thing - file not in scheme.

How does one add a file to a scheme... I don't know - cann't tell.  So looking closer at the project there is YET ANOTHER place to add a Swift file... counting - that 3 places.  And I don't remember being told which or any place a new file should be placed in the Getting Started or Docs.

Searching... nothing...

If you were a developer where would you create a new file:  Darwin/Sources/   OR Sources/Skip/  OR  App/   each has a certain logic to being the place to put a new file.

Then there is the fact that HelloSkipAppMain.swift lives in multiple places...
Then there is:
 - HelloSkipApp
 - HelloSkip
 
Where SHOULD I put a new file?

**Comment by marcprux** [comment]
This was responded to in the discussion at https://github.com/skiptools/skip/discussions/52, so I'll close this and the thread can be continued there.
