### ISSUE TITLE
Gradle run error: Optional(SkipDriveExternal.ProcessResult.ExitStatus.terminated(code: 1))

### ISSUE THREAD

**Issue by oluarry** [skiptools/skip#7]
This error pops up when I run build in xcode, I have Android studio device running.
<img width="1402" alt="Screenshot 2023-10-27 at 1 07 39 PM" src="https://github.com/skiptools/skip/assets/47468239/1ef304b0-01e6-4805-8d4b-231a0bb8bc72">

**Comment by nikhiljainlive** [comment]
I am facing the same issue, did you resolve this error?

<img width="1509" alt="Screenshot 2023-10-28 at 3 49 19 PM" src="https://github.com/skiptools/skip/assets/47408125/5b2c2a2a-8d5f-491f-a00d-9513b1890ce7">

**Comment by marcprux** [comment]
We released Skip 0.7.13 last night, which might help address this issue. Run `skip upgrade` from the command line and then ensure `skip checkup` passes to get the latest version. If it fails, please post the output of `skip checkup --verbose`.

They you'll then need to run Xcode's `File` -> `Packages` -> `Update to Latest Package Versions` to get the Skip 0.7.13 plugin, please try again and let us know if it still fails.

The "Grade run error" is a generic catch-all failure condition for "something went wrong". To get more details on the failure, go to the `Report Navigator` in Xcode (CMD-9) and find the most recent failure, then expand the log message with the red error indicator. That information will help us isolate the problem further.
