### ISSUE TITLE
Error while building at first install

### ISSUE THREAD

**Issue by DominatorVbN** [skiptools/skip#8]
Error while building at first install:

```
The expected gradle folder did not exist, which may mean the Skip transpiler is not enabled or encountered errors. Try running `skip doctor` to diagnose and re-building the project. See https://skip.tools/docs/. Missing path: ~/Library/Developer/Xcode/DerivedData/SkipTour-afstayrnnummvzgvfbhngngipjkd/SourcePackages/plugins/Playing.output/SkipTour/skipstone/SkipTour
```

**Comment by DominatorVbN** [comment]
Results from `skip doctor`

```
➜  SkipTour skip doctor
Skip Doctor
[✓] Skip version 0.7.13 (= 0.7.13)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.1.17 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2022.3
[✓] Check Skip Updates: 0.7.13
[✓] Skip (0.7.13) checks complete
➜  SkipTour 

```

**Comment by DominatorVbN** [comment]
Additional info found out the root cause of the issue is:
in case of a path where the parent directory have space in it's name this returns incorrect project name

```
PROJECT=$(basename ${PROJECT_DIR})
```

**Comment by marcprux** [comment]
Thanks for the report, and the workaround. I'll look into the path-with-space issue, but I'm not surprised; paths with spaces are a recipe for trouble with Android and Gradle. We'll make a note of it in the FAQ.

Combined with your comment at https://github.com/skiptools/skip/issues/5, I'm hoping this means you've resolved your issues so far, so I'll close this one. Please re-open it with more information if you still have problems.
