### ISSUE TITLE
skip checkup - could not find or install Android Studio. Command line install worked. 

### ISSUE THREAD

**Issue by dkllj** [skiptools/skip#80]
I had this issue when running skip checkup.

- Ran skip checkup multiple times and it could not find Android Studio (even though it was installed) and tried to install it. 
- uninstalled Android Studio using Jetbrains Toolbox 
- ran skip checkup and it did not find Android Studio
- successfully ran brew install android-studio from command line(see log)
- successfully ran skip checkup

[✓] Skip version 0.7.45 (= 0.7.45)
[✓] macOS version 14.2.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.2.3 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
**[!] Android Studio not found: brew install android-studio**
[✓] Resolve dependencies (6.02s)
[✓] Build hello-skip (13.08s)
[✓] Test Swift (9.15s)
[✓] Test Kotlin (17.17s)
[✓] Archive iOS ipa (11.01s)
[✓] Assemble HelloSkip-release.ipa (0.01s)
[✓] Verify HelloSkip-release.ipa 23 KB
[✓] Assembling Android apk (35.11s)
[✓] Verify HelloSkip-release.apk 6.2 MB
[✓] Check Swift Package (0.49s)
[!] Skip 0.7.45 checkup (92.7s)

brew install android-studio
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##################################################################################### 100.0%
==> Downloading https://redirector.gvt1.com/edgedl/android/studio/install/2023.1.1.27/androi
==> Downloading from https://r4---sn-o097znzr.gvt1.com/edgedl/android/studio/install/2023.1.
##################################################################################### 100.0%
==> Installing Cask android-studio
==> Moving App 'Android Studio.app' to '/Applications/Android Studio.app'
==> Linking Binary 'studio' to '/opt/homebrew/bin/studio'
🍺  android-studio was successfully installed!
              
[✓] Skip version 0.7.45 (= 0.7.45)
[✓] macOS version 14.2.1 (> 13.5.0)
[✓] Swift version 5.9 (= 5.9.0)
[✓] Xcode version 15.0.1 (> 15.0.0)
[✓] Homebrew version 4.2.3 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
**[✓] Android Studio version: 2023.1**
[✓] Resolve dependencies (6.15s)
[✓] Build hello-skip (12.77s)
[✓] Test Swift (8.64s)
[✓] Test Kotlin (17.18s)
[⣦] Archive iOS ipa: Fetching from https://source.skip.tools/skip-unit.git (cached)

**Comment by aabewhite** [comment]
Thank you for the report!

**Comment by marcprux** [comment]
This appears to have been resolved in https://github.com/skiptools/skip/issues/84. Closing this issue, but please re-open if the issue persists.
