### ISSUE TITLE
Issue when the project starts. doesn't build the project.

### ISSUE THREAD

**Issue by dgnsstyles** [skiptools/skip#83]
Command PhaseScriptExecution failed with a nonzero exit code
in a fresh Skip project.
![Captura de pantalla 2024-01-18 a la(s) 10 32 50](https://github.com/skiptools/skip/assets/16584515/de90540e-0823-4ba2-8903-0db1c1549ad4)
and fail in the beginning. in the previous versions doesn't not have this issue.

**Comment by marcprux** [comment]
Can you let us know the command you used to initialize the project? Also, can you let us know if `skip checkup -v` passes?

**Comment by dgnsstyles** [comment]
yes the command `skip checkup -v` passes, and my command it's ` skip init --open-xcode --appid=com.xyz.HelloSkip hello-skip HelloSkip` the same of the documentation.

**Comment by marcprux** [comment]
Could you run the `skip init` command with the `-v` flag for verbose logging and post the result? That might help us identify the cause of the problem.

**Comment by dgnsstyles** [comment]
executing command: /usr/bin/swift package dump-package --package-path /Users/davidgoren/Documents/swift/hello-skip
warning: 'hello-skip': /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/davidgoren/Documents/swift/hello-skip/Package.swift -target arm64-apple-macosx13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -vfsoverlay /var/folders/f_/5fy7swmj27n__2dwqpqr8lqc0000gn/T/TemporaryDirectory.MJOBfD/vfs.yaml -swift-version 5 -package-description-version 5.9.0 -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -disable-implicit-concurrency-module-import -disable-implicit-string-processing-module-import -empty-abi-descriptor -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -module-name main -disable-clang-spi -target-sdk-version 14.2 -target-sdk-name macosx14.2 -external-plugin-path '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server' -external-plugin-path '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/bin/swift-plugin-server' -external-plugin-path '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server' -external-plugin-path '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server' -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -o /var/folders/f_/5fy7swmj27n__2dwqpqr8lqc0000gn/T/TemporaryDirectory.CjhFbX/Package-1.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang /var/folders/f_/5fy7swmj27n__2dwqpqr8lqc0000gn/T/TemporaryDirectory.CjhFbX/Package-1.o -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk --target=arm64-apple-macosx13.0 -force_load /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCompatibilityPacks.a -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/swift -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -lPackageDescription -Xlinker -rpath -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI -o /var/folders/f_/5fy7swmj27n__2dwqpqr8lqc0000gn/T/TemporaryDirectory.kkOIbu/hello-skip-manifest
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0
{
  "cLanguageStandard" : null,
  "cxxLanguageStandard" : null,
  "dependencies" : [
    {
      "sourceControl" : [
        {
          "identity" : "skip",
          "location" : {
            "remote" : [
              {
                "urlString" : "https://source.skip.tools/skip.git"
              }
            ]
          },
          "productFilter" : null,
          "requirement" : {
            "range" : [
              {
                "lowerBound" : "0.7.45",
                "upperBound" : "1.0.0"
              }
            ]
          }
        }
      ]
    },
    {
      "sourceControl" : [
        {
          "identity" : "skip-ui",
          "location" : {
            "remote" : [
              {
                "urlString" : "https://source.skip.tools/skip-ui.git"
              }
            ]
          },
          "productFilter" : null,
          "requirement" : {
            "range" : [
              {
                "lowerBound" : "0.0.0",
                "upperBound" : "1.0.0"
              }
            ]
          }
        }
      ]
    }
  ],
  "name" : "hello-skip",
  "packageKind" : {
    "root" : [
      "/Users/davidgoren/Documents/swift/hello-skip"
    ]
  },
  "pkgConfig" : null,
  "platforms" : [
    {
      "options" : [
      ],
      "platformName" : "ios",
      "version" : "16.0"
    },
    {
      "options" : [
      ],
      "platformName" : "macos",
      "version" : "13.0"
    },
    {
      "options" : [
      ],
      "platformName" : "tvos",
      "version" : "16.0"
    },
    {
      "options" : [
      ],
      "platformName" : "watchos",
      "version" : "9.0"
    },
    {
      "options" : [
      ],
      "platformName" : "maccatalyst",
      "version" : "16.0"
    }
  ],
  "products" : [
    {
      "name" : "HelloSkipApp",
      "settings" : [
      ],
      "targets" : [
        "HelloSkip"
      ],
      "type" : {
        "library" : [
          "dynamic"
        ]
      }
    }
  ],
  "providers" : null,
  "swiftLanguageVersions" : null,
  "targets" : [
    {
      "dependencies" : [
        {
          "product" : [
            "SkipUI",
            "skip-ui",
            null,
            null
          ]
        }
      ],
      "exclude" : [
      ],
      "name" : "HelloSkip",
      "packageAccess" : true,
      "pluginUsages" : [
        {
          "plugin" : [
            "skipstone",
            "skip"
          ]
        }
      ],
      "resources" : [
        {
          "path" : "Resources",
          "rule" : {
            "process" : {
            }
          }
        }
      ],
      "settings" : [
      ],
      "type" : "regular"
    },
    {
      "dependencies" : [
        {
          "byName" : [
            "HelloSkip",
            null
          ]
        },
        {
          "product" : [
            "SkipTest",
            "skip",
            null,
            null
          ]
        }
      ],
      "exclude" : [
      ],
      "name" : "HelloSkipTests",
      "packageAccess" : true,
      "pluginUsages" : [
        {
          "plugin" : [
            "skipstone",
            "skip"
          ]
        }
      ],
      "resources" : [
        {
          "path" : "Resources",
          "rule" : {
            "process" : {
            }
          }
        }
      ],
      "settings" : [
      ],
      "type" : "test"
    }
  ],
  "toolsVersion" : {
    "_version" : "5.9.0"
  }
}

**Comment by dgnsstyles** [comment]
up is the output on the build side with init -v.

**Comment by dgnsstyles** [comment]
![Captura de pantalla 2024-01-18 a la(s) 16 21 39](https://github.com/skiptools/skip/assets/16584515/22ca24fe-9805-4892-ae57-a926156758e6)

two issues... but i got the licence. in skiptools.env. the another one i don't know why...!!!

**Comment by marcprux** [comment]
Note that the name of the file should be "skipkey.env", not "skiptools.env". Can you check the contents of the `~/.skiptools/skiptools.env` file, and make sure it looks like:

```
SKIPKEY: SKP23E4…
```

The `.sourcehash` error is likely a side-effect of the license error, so once that one is resolved, try cleaning the build folder and re-building.

**Comment by dgnsstyles** [comment]
Thank you @marcprux
