### ISSUE TITLE
Had issues with “skip init”. This command created a project that works.

### ISSUE THREAD

**Issue by dkllj** [skiptools/skip#84]
I got various build errors after using skip init. My guess is that at lease the appid and module need to be unique.

      -  skip init --open-xcode --appid=com.lms.log LMSLogModule LMSLog

**Comment by marcprux** [comment]
I assume this is in reference to https://github.com/skiptools/skip/issues/80. Glad to see you got it working! You didn't mention the `skip init` parameters you used that caused the original failure, but if you encounter the issue again, please do let us know.

**Comment by dkllj** [comment]
These created projects that didn’t build.  It’s not an issue for me since I have a working project. But it might be worthwhile to have a check for it in skip init. 

skip init --open-xcode --appid=com.lms.LMSLog  LMSLog LMSLog
skip init --open-xcode --appid=com.lms.lmsLogView  logView lmsLogView
skip init --open-xcode --appid=com.lms.lmsLogView  logView lmsLogView3
