### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code - SkipStone plugin missing output 

### ISSUE THREAD

**Issue by Thomaslegravier** [skiptools/skip#85]
Hello team,
I have an issue on the build of the HelloSkip example project. 
I followed your Readme and the `skip checkup` seems to be ok. 

The problem seems to coming from the SkipStone plugin. I trusted the plugin in Xcode but on build the SkipStone output seems to missing. 
My `~/.skiptools/skipkey.env` file have a valid license key & the Android simulator is launched.

Project init:
<img width="888" alt="Capture d’écran 2024-01-19 à 10 24 54" src="https://github.com/skiptools/skip/assets/1955277/fa7207e1-d55f-4e93-a881-b10d6410cd94">

Skip checkup:
<img width="416" alt="Capture d’écran 2024-01-19 à 10 25 08" src="https://github.com/skiptools/skip/assets/1955277/6b90c64c-de32-4616-9ef0-ddc9fe71643c">

On build, I always have this error, even with the Showcase example app:
<img width="1129" alt="Capture d’écran 2024-01-19 à 10 37 25" src="https://github.com/skiptools/skip/assets/1955277/c130ed23-1092-47af-944c-ed88f4ad8f3a">

Do you have some recommandations for that?

**Comment by marcprux** [comment]
From this error I'm guessing the format of your `~/.skiptools/skipkey.env` file is invalid:

```
note: Skip 0.7.45: transpile plugin to: /Users/thomaslegravier/Desktop/eee/hello-skip/.build/plugins/outputs/hello-skip/HelloSkip/skipstone/HelloSkip/src/main at 10:42:25
Error: expected colon, near ""
[✗] Build hello-skip (5.25s)
```

Can you check to ensure that the contents look like:

```
SKIPKEY: SKIP101010…10101PKS
```

**Comment by Thomaslegravier** [comment]
Great ! It's working now. Thx @marcprux
