### ISSUE TITLE
Support for AsyncStream

### ISSUE THREAD

**Issue by jefflewis** [skiptools/skip#87]
AsyncStream doesn't appear to be supported.
![CleanShot 2024-01-24 at 08 48 44@2x](https://github.com/skiptools/skip/assets/4528172/79f6d8a9-428c-4673-b111-fcc4935a2ced)

**Comment by pnewell** [comment]
This is also high up on my list of limitations I've run into / had to spend a bunch of time working around

**Comment by aabewhite** [comment]
Skip now supports AsyncStream and related API! Let us know if you run into any issues.
