### ISSUE TITLE
I can run Skip because gradle command failed when i open in Android Studio works fine but in XCode doesn't  work....

### ISSUE THREAD

**Issue by dgnsstyles** [skiptools/skip#89]
The gradle command failed. Review the log for details and consult https://skip.tools/docs/faq for common solutions. Command: gradle -p ../Android launchDebug.

[✓] Skip version 0.7.55 (= 0.7.55)
[✓] macOS version 14.0 (> 13.5.0)
[✓] Swift version 5.9.2 (> 5.9.0)
[✓] Xcode version 15.2 (> 15.0.0)
[✓] Xcode tools SDKs: 8
[✓] Homebrew version 4.2.6 (> 4.1.0)
[✓] Gradle version 8.4 (> 8.3.0)
[✓] Java version 17.0.9 (> 17.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2023.1
[✓] Android SDK licenses: 7
[✓] Resolve dependencies (11.17s)
[✓] Build hello-skip (15.77s)
[✓] Test Swift (9.19s)
[✓] Test Kotlin (45.74s)
[✓] Archive iOS ipa (27.08s)
[✓] Assemble HelloSkip-release.ipa (0.02s)
[✓] Verify HelloSkip-release.ipa 24 KB
[⡇] Verify HelloSkip-release.apk: /var/folders/f_/5fy7swmj27n__2dwqpqr8lqc0000gn/T//82C0BDE7-3F82-41B4-997F-3AD522AA1750/hello-skip/.build/Android/app/outputs/apk/release/app-release-unsigned.apk[✓] Assembling Android apk (101.14s)
[✓] Verify HelloSkip-release.apk 6,2 MB
[✓] Check Swift Package (1.87s)
[✓] Skip 0.7.55 checkup (215.11s)

results of skip checkup.

**Comment by marcprux** [comment]
Can you try `skip upgrade` to 0.8.3, and then see if `skip checkup` passes? If so, you should be able to create a new project with `skip init` and it should run.

**Comment by dbsghdz1** [comment]
i have same issue
