### ISSUE TITLE
Not able to build after skit init

### ISSUE THREAD

**Issue by naticio** [skiptools/skip#91]
I'm not able to build for some reason, checkup all good, init ok, I clean build folder and deleted derived data but same issue persist

![image](https://github.com/skiptools/skip/assets/34293050/96d0814f-41e2-42eb-9a4a-c4a7076cee2e)

**Comment by aabewhite** [comment]
How did you generate the project you're building? It looks like something is messed up in the build configuration.

**Comment by naticio** [comment]
I used this command
skip init --open-xcode --appid=myBundleID nameofmyproject Max

**Comment by aabewhite** [comment]
Well nothing wrong with that!

Did you by chance have an old project with the same name?

Please try:

>> brew update
>> brew upgrade skip

Then - assuming you haven't done any work in Max - delete the old Max project and re-run skip-init to get a new project.
Also please delete Xcode's Derived Data folder and restart Xcode before attempting to build the new project.

**Comment by santaman217** [comment]
I am having a similar issue and have tried all of the fixes mentioned here but I am still unable to build the project. I can post error logs if you think it would help.

**Comment by aabewhite** [comment]
> I am having a similar issue and have tried all of the fixes mentioned here but I am still unable to build the project. I can post error logs if you think it would help.

Yes please!

**Comment by aabewhite** [comment]
Yes please!

**Comment by santaman217** [comment]
I hope posting an image is okay as copying each error code in Xcode is a pain. 
<img width="1193" alt="Screenshot 2024-04-01 at 17 28 49" src="https://github.com/skiptools/skip/assets/62559014/a92c0c2e-2cd0-4190-a911-71ae385608b1">

**Comment by aabewhite** [comment]
Thanks! And can you please post the command you used to create the MyAndroidApp project?

**Comment by santaman217** [comment]
skip init --open-xcode --appid=com.example MyAndroidApp MyAndroidApp

**Comment by aabewhite** [comment]
Thanks again. The problem may be related to the project name and app name being the same. Can you please try deleting Xcode's DerivedData folder (or at least the MyAndroidApp folder within it) and then run the command with a different project name? Eg:

skip init --open-xcode --appid=com.example my-android-app MyAndroidApp

That worked for me.

**Comment by santaman217** [comment]
It completely worked, thank you so much!

Have a nice day!!

**Comment by aabewhite** [comment]
Excellent! I've updated the documentation to make this restriction clear, and we'll enhance the tools to prevent this type of error in a future version.
