### ISSUE TITLE
skip checkup  error

### ISSUE THREAD

**Issue by zenghuayang** [skiptools/skip#96]
```
[✓] Skip version 0.8.15 (= 0.8.15)
[✓] macOS version 14.3 (> 13.5.0)
[✓] Swift version 5.9.2 (> 5.9.0)
[✓] Xcode version 15.2 (> 15.0.0)
[✓] Xcode tools SDKs: 5
[✓] Homebrew version 4.2.9 (> 4.1.0)
[✓] Gradle version 8.6 (= 8.6.0)
[✓] Java version 21.0.2 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2023.1
[✓] Android tools SDKs: 7
[✓] Resolve dependencies (14.4s)
[✓] Build hello-skip (12.65s)
[✓] Test Swift (6.96s)
[✓] Test Kotlin (35.52s)
[✓] Archive iOS ipa (22.55s)
[✓] Assemble HelloSkip-release.ipa (0.01s)
[✓] Verify HelloSkip-release.ipa 24 KB
[✗] Assembling Android apk (28.39s)
[✗] Verify HelloSkip-release.apk: The file “app-release-unsigned.apk” couldn’t be opened because there is no such file.
[✓] Check Swift Package (0.4s)
[✗] Skip 0.8.15 checkup fail (log: /tmp/skip-checkup-.txt)
See https://skip.tools/docs/faq and https://community.skip.tools for resolution
Error: 3 errors
```

**Comment by zenghuayang** [comment]
> ```
> [✓] Skip version 0.8.15 (= 0.8.15)
> [✓] macOS version 14.3 (> 13.5.0)
> [✓] Swift version 5.9.2 (> 5.9.0)
> [✓] Xcode version 15.2 (> 15.0.0)
> [✓] Xcode tools SDKs: 5
> [✓] Homebrew version 4.2.9 (> 4.1.0)
> [✓] Gradle version 8.6 (= 8.6.0)
> [✓] Java version 21.0.2 (> 21.0.0)
> [✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
> [✓] Android Studio version: 2023.1
> [✓] Android tools SDKs: 7
> [✓] Resolve dependencies (14.4s)
> [✓] Build hello-skip (12.65s)
> [✓] Test Swift (6.96s)
> [✓] Test Kotlin (35.52s)
> [✓] Archive iOS ipa (22.55s)
> [✓] Assemble HelloSkip-release.ipa (0.01s)
> [✓] Verify HelloSkip-release.ipa 24 KB
> [✗] Assembling Android apk (28.39s)
> [✗] Verify HelloSkip-release.apk: The file “app-release-unsigned.apk” couldn’t be opened because there is no such file.
> [✓] Check Swift Package (0.4s)
> [✗] Skip 0.8.15 checkup fail (log: /tmp/skip-checkup-.txt)
> See https://skip.tools/docs/faq and https://community.skip.tools for resolution
> Error: 3 errors
> ```

skip doctor is correct

```
Skip Doctor
[✓] Skip version 0.8.15 (= 0.8.15)
[✓] macOS version 14.3 (> 13.5.0)
[✓] Swift version 5.9.2 (> 5.9.0)
[✓] Xcode version 15.2 (> 15.0.0)
[✓] Xcode tools SDKs: 5
[✓] Homebrew version 4.2.9 (> 4.1.0)
[✓] Gradle version 8.6 (= 8.6.0)
[✓] Java version 21.0.2 (> 21.0.0)
[✓] Android Debug Bridge version 1.0.41 (> 1.0.40)
[✓] Android Studio version: 2023.1
[✓] Android tools SDKs: 7
[✓] Check Skip Updates: 0.8.15
[✓] Skip (0.8.15) checks complete
```

**Comment by zenghuayang** [comment]
`skip checkup --verbose`
[skip-checkup-.txt](https://github.com/skiptools/skip/files/14367576/skip-checkup-.txt)

**Comment by aabewhite** [comment]
Thank you for the log! The relevant error is from the Swift compiler:

```
[305/307] Compiling HelloSkip ContentView.swift
rosetta error: Failed to open libRosettaRuntime
 <unknown>:0: warning: compiler plugin not loaded: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server; failed to initialize
```

This indicates that you're on an Apple Silicon Mac, but that your command line tools are compiled for Intel. Typically this happens when your Homebrew installation was migrated from an Intel Mac. Is that the case? If so, you'll want to re-install Homebrew and then use it to re-install Skip.

**Comment by marcprux** [comment]
We're hoping that the last comment helped resolve the issue. If not, please re-open this issue (or create a new one) and we will continue to seek solutions.
