### ISSUE TITLE
Skip checkup error / Error: the file payload doesn't exist 

### ISSUE THREAD

**Issue by PavelKurzo** [skiptools/skip#97]
Hey everyone, I want to share my problem and the solution. The command "skip checkup" was not passing all the tests/points, as you can see on the screenshot. I tried everything, from updating all the components like Xcode, dev tools, and command line tools, but nothing was working or helping. The main issue was that my terminal was running with Rosetta. To test this, you can run "brew config," and Rosetta 2 should be false. After removing the checkmark from running with Rosetta and reinstalling all the components, the "skip checkup" passed successfully.

![screenshot](https://github.com/skiptools/skip/assets/72884798/5ccb6a46-ce31-4409-b80f-ba62cdc821ea)

I've got macbook pro m1 2020 / macOS 14.3.1

**Comment by marcprux** [comment]
Wow, that never occurred to me as a possibility. I've added a check in `skip doctor` and `skip checkup` to identify and warn about this situation.

Thanks for the investigation and letting us know the solution!
